import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/MainHeader";
// import MenuCategories from "@/components/MenuCategories";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NEWS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={" bg-[#111827]"}>
          <MainHeader />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
